;
; File generated by cc65 v 2.17 - Git 180bb082
;
	.fopt		compiler,"cc65 v 2.17 - Git 180bb082"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_led_init
	.import		_led_set
	.import		_delay_ms
	.import		_uart_init
	.import		_uart_puts
	.import		_uart_printf
	.import		_uart_handler
	.import		_ps2_init
	.export		_sys_banner
	.export		_mdelay
	.export		_main

.segment	"DATA"

_sys_banner:
	.byte	$68,$63,$36,$35,$30,$32,$20,$73,$79,$73,$74,$65,$6D,$20,$62,$75
	.byte	$69,$6C,$64,$74,$69,$6D,$65,$20,$5B,$31,$39,$3A,$31,$32,$3A,$30
	.byte	$33,$20,$4A,$61,$6E,$20,$20,$33,$20,$32,$30,$31,$39,$5D,$20,$72
	.byte	$65,$76,$20,$76,$31,$2E,$30,$00

.segment	"RODATA"

L000F:
	.byte	$36,$35,$30,$32,$20,$48,$6F,$6D,$65,$43,$6F,$6D,$70,$75,$74,$65
	.byte	$72,$20,$72,$65,$61,$64,$79,$2E,$0D,$0A,$00
L0018	:=	L000F+0
L0027:
	.byte	$75,$61,$72,$74,$5F,$70,$72,$69,$6E,$74,$66,$20,$74,$65,$73,$74
	.byte	$20,$5B,$25,$73,$5D,$0D,$0A,$00
L002B:
	.byte	$73,$69,$7A,$65,$6F,$66,$28,$63,$68,$61,$72,$29,$3A,$20,$20,$25
	.byte	$64,$20,$0D,$0A,$00
L002F:
	.byte	$73,$69,$7A,$65,$6F,$66,$28,$73,$68,$6F,$72,$74,$29,$3A,$20,$25
	.byte	$64,$20,$0D,$0A,$00
L0037:
	.byte	$73,$69,$7A,$65,$6F,$66,$28,$6C,$6F,$6E,$67,$29,$3A,$20,$25,$64
	.byte	$20,$0D,$0A,$00
L0021:
	.byte	$75,$61,$72,$74,$20,$74,$65,$73,$74,$20,$73,$74,$61,$72,$74,$2E
	.byte	$0D,$0A,$00
L0033:
	.byte	$73,$69,$7A,$65,$6F,$66,$28,$69,$6E,$74,$29,$3A,$20,$25,$64,$20
	.byte	$0D,$0A,$00
L003B:
	.byte	$56,$49,$41,$31,$5F,$50,$41,$30,$3A,$20,$25,$6C,$78,$20,$0D,$0A
	.byte	$00
L0024:
	.byte	$75,$61,$72,$74,$20,$74,$65,$73,$74,$20,$6F,$6B,$2E,$0D,$0A,$00

; ---------------------------------------------------------------
; void __near__ mdelay (int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_mdelay: near

.segment	"CODE"

	ldy     #$00
	lda     (sp),y
	jsr     _delay_ms
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; long __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$0A
	jsr     pusha0
	ldy     #$00
	jsr     _uart_init
	ldy     #$00
	jsr     _led_init
	lda     #<(L000F)
	ldx     #>(L000F)
	jsr     pushax
	jsr     _uart_puts
	jmp     L0013
L0011:	lda     #$01
	jsr     _led_set
	lda     #<(L0018)
	ldx     #>(L0018)
	jsr     pushax
	jsr     _uart_puts
	ldx     #$01
	lda     #$F4
	jsr     pushax
	jsr     _mdelay
	lda     #$00
	jsr     _led_set
	ldx     #$01
	lda     #$F4
	jsr     pushax
	jsr     _mdelay
L0013:	jsr     ldax0sp
	sta     regsave
	stx     regsave+1
	jsr     decax1
	jsr     stax0sp
	lda     regsave
	ora     regsave+1
	bne     L0011
	lda     #<(L0021)
	ldx     #>(L0021)
	jsr     pushax
	jsr     _uart_puts
	lda     #<(L0024)
	ldx     #>(L0024)
	jsr     pushax
	jsr     _uart_puts
	lda     #<(L0027)
	ldx     #>(L0027)
	jsr     pushax
	lda     #<(_sys_banner)
	ldx     #>(_sys_banner)
	jsr     pushax
	ldy     #$04
	jsr     _uart_printf
	lda     #<(L002B)
	ldx     #>(L002B)
	jsr     pushax
	lda     #$01
	jsr     pusha0
	ldy     #$04
	jsr     _uart_printf
	lda     #<(L002F)
	ldx     #>(L002F)
	jsr     pushax
	lda     #$02
	jsr     pusha0
	ldy     #$04
	jsr     _uart_printf
	lda     #<(L0033)
	ldx     #>(L0033)
	jsr     pushax
	lda     #$02
	jsr     pusha0
	ldy     #$04
	jsr     _uart_printf
	lda     #<(L0037)
	ldx     #>(L0037)
	jsr     pushax
	lda     #$04
	jsr     pusha0
	tay
	jsr     _uart_printf
	lda     #<(L003B)
	ldx     #>(L003B)
	jsr     pushax
	ldx     #$00
	lda     #$20
	sta     sreg
	lda     #$7F
	sta     sreg+1
	lda     #$A0
	jsr     pusheax
	ldy     #$06
	jsr     _uart_printf
	ldy     #$00
	jsr     _ps2_init
L0042:	ldy     #$00
	jsr     _uart_handler
	jmp     L0042

.endproc

