;
; File generated by cc65 v 2.17 - Git 180bb08
;
	.fopt		compiler,"cc65 v 2.17 - Git 180bb08"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_strtoul
	.import		_strcmp
	.import		_strlen
	.import		_memset
	.import		_uart_printf
	.import		_gpio_init
	.import		_gpio_write
	.import		_gpio_read
	.import		_ps2_process
	.import		_vga_ctrl
	.export		_shell_cmd
	.export		_argc
	.export		_argv
	.export		_ci
	.export		_cook
	.export		_gi
	.export		_gi_get
	.export		_shell

.segment	"DATA"

_shell_cmd:
	.word	$0000
_argv:
	.word	$0000
	.res	10,$00
_ci:
	.addr	L000C
	.addr	_cmd_read
	.addr	L000F
	.addr	L0011
	.addr	_cmd_write
	.addr	L0014
	.addr	L0016
	.addr	_cmd_exec
	.addr	L0019
	.addr	L001B
	.addr	_cmd_dumpw
	.addr	L001E
	.addr	L0020
	.addr	_cmd_dumpb
	.addr	L0023
	.addr	L0025
	.addr	_cmd_gpio
	.addr	L0028
	.addr	L002A
	.addr	_cmd_ps2
	.addr	L002D
	.addr	L002F
	.addr	_cmd_vga
	.addr	L0032
	.addr	L0034
	.addr	_cmd_help
	.addr	L0037
_gi:
	.byte	$56,$49,$41,$31,$5F,$50,$41,$30,$00
	.res	7,$00
	.dword	$7F2000A0
	.byte	$56,$49,$41,$31,$5F,$50,$41,$31,$00
	.res	7,$00
	.dword	$7F2000A1
	.byte	$56,$49,$41,$31,$5F,$50,$41,$32,$00
	.res	7,$00
	.dword	$7F2000A2
	.byte	$56,$49,$41,$31,$5F,$50,$41,$33,$00
	.res	7,$00
	.dword	$7F2000A3
	.byte	$56,$49,$41,$31,$5F,$50,$41,$34,$00
	.res	7,$00
	.dword	$7F2000A4
	.byte	$56,$49,$41,$31,$5F,$50,$41,$35,$00
	.res	7,$00
	.dword	$7F2000A5
	.byte	$56,$49,$41,$31,$5F,$50,$41,$36,$00
	.res	7,$00
	.dword	$7F2000A6
	.byte	$56,$49,$41,$31,$5F,$50,$41,$37,$00
	.res	7,$00
	.dword	$7F2000A7
	.byte	$56,$49,$41,$31,$5F,$50,$42,$30,$00
	.res	7,$00
	.dword	$7F2000B0
	.byte	$56,$49,$41,$31,$5F,$50,$42,$31,$00
	.res	7,$00
	.dword	$7F2000B1
	.byte	$56,$49,$41,$31,$5F,$50,$42,$32,$00
	.res	7,$00
	.dword	$7F2000B2
	.byte	$56,$49,$41,$31,$5F,$50,$42,$33,$00
	.res	7,$00
	.dword	$7F2000B3
	.byte	$56,$49,$41,$31,$5F,$50,$42,$34,$00
	.res	7,$00
	.dword	$7F2000B4
	.byte	$56,$49,$41,$31,$5F,$50,$42,$35,$00
	.res	7,$00
	.dword	$7F2000B5
	.byte	$56,$49,$41,$31,$5F,$50,$42,$36,$00
	.res	7,$00
	.dword	$7F2000B6
	.byte	$56,$49,$41,$31,$5F,$50,$42,$37,$00
	.res	7,$00
	.dword	$7F2000B7
	.byte	$56,$49,$41,$32,$5F,$50,$41,$30,$00
	.res	7,$00
	.dword	$7F4000A0
	.byte	$56,$49,$41,$32,$5F,$50,$41,$31,$00
	.res	7,$00
	.dword	$7F4000A1
	.byte	$56,$49,$41,$32,$5F,$50,$41,$32,$00
	.res	7,$00
	.dword	$7F4000A2
	.byte	$56,$49,$41,$32,$5F,$50,$41,$33,$00
	.res	7,$00
	.dword	$7F4000A3
	.byte	$56,$49,$41,$32,$5F,$50,$41,$34,$00
	.res	7,$00
	.dword	$7F4000A4
	.byte	$56,$49,$41,$32,$5F,$50,$41,$35,$00
	.res	7,$00
	.dword	$7F4000A5
	.byte	$56,$49,$41,$32,$5F,$50,$41,$36,$00
	.res	7,$00
	.dword	$7F4000A6
	.byte	$56,$49,$41,$32,$5F,$50,$41,$37,$00
	.res	7,$00
	.dword	$7F4000A7
	.byte	$56,$49,$41,$32,$5F,$50,$42,$30,$00
	.res	7,$00
	.dword	$7F4000B0
	.byte	$56,$49,$41,$32,$5F,$50,$42,$31,$00
	.res	7,$00
	.dword	$7F4000B1
	.byte	$56,$49,$41,$32,$5F,$50,$42,$32,$00
	.res	7,$00
	.dword	$7F4000B2
	.byte	$56,$49,$41,$32,$5F,$50,$42,$33,$00
	.res	7,$00
	.dword	$7F4000B3
	.byte	$56,$49,$41,$32,$5F,$50,$42,$34,$00
	.res	7,$00
	.dword	$7F4000B4
	.byte	$56,$49,$41,$32,$5F,$50,$42,$35,$00
	.res	7,$00
	.dword	$7F4000B5
	.byte	$56,$49,$41,$32,$5F,$50,$42,$36,$00
	.res	7,$00
	.dword	$7F4000B6
	.byte	$56,$49,$41,$32,$5F,$50,$42,$37,$00
	.res	7,$00
	.dword	$7F4000B7

.segment	"RODATA"

L000F:
	.byte	$72,$20,$20,$20,$20,$20,$5B,$61,$64,$64,$72,$5D,$20,$20,$20,$20
	.byte	$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$20,$20,$20,$72,$65,$61,$64,$20,$20,$20,$20,$61,$6E
	.byte	$79,$20,$61,$64,$64,$72,$00
L0019:
	.byte	$78,$20,$20,$20,$20,$20,$5B,$61,$64,$64,$72,$5D,$20,$20,$20,$20
	.byte	$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$20,$20,$20,$65,$78,$65,$63,$75,$74,$65,$20,$61,$6E
	.byte	$79,$20,$61,$64,$64,$72,$00
L0014:
	.byte	$77,$20,$20,$20,$20,$20,$5B,$61,$64,$64,$72,$5D,$20,$5B,$64,$61
	.byte	$74,$61,$5D,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$20,$20,$20,$77,$72,$69,$74,$65,$20,$20,$20,$61,$6E
	.byte	$79,$20,$61,$64,$64,$72,$00
L0023:
	.byte	$64,$75,$6D,$70,$62,$20,$5B,$61,$64,$64,$72,$5D,$20,$5B,$62,$79
	.byte	$74,$65,$5F,$6E,$75,$6D,$5D,$20,$20,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$20,$20,$20,$64,$75,$6D,$70,$20,$20,$20,$20,$61,$6E
	.byte	$79,$20,$61,$64,$64,$72,$00
L001E:
	.byte	$64,$75,$6D,$70,$77,$20,$5B,$61,$64,$64,$72,$5D,$20,$5B,$77,$6F
	.byte	$72,$64,$5F,$6E,$75,$6D,$5D,$20,$20,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$20,$20,$20,$64,$75,$6D,$70,$20,$20,$20,$20,$61,$6E
	.byte	$79,$20,$61,$64,$64,$72,$00
L002D:
	.byte	$70,$73,$32,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$20,$20,$20,$72,$65,$61,$64,$20,$70,$73,$32,$20,$69
	.byte	$6E,$70,$75,$74,$00
L0037:
	.byte	$68,$65,$6C,$70,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$20,$20,$20,$70,$72,$69,$6E,$74,$20,$63,$6D,$64,$20
	.byte	$69,$6E,$66,$6F,$00
L0028:
	.byte	$67,$70,$69,$6F,$20,$20,$69,$6E,$69,$74,$7C,$72,$65,$61,$64,$7C
	.byte	$77,$72,$69,$74,$65,$20,$5B,$56,$49,$41,$31,$5F,$50,$41,$30,$2E
	.byte	$2E,$2E,$5D,$20,$20,$20,$63,$74,$72,$6C,$20,$61,$6E,$79,$20,$67
	.byte	$70,$69,$6F,$00
L0032:
	.byte	$76,$67,$61,$20,$20,$20,$63,$6D,$64,$20,$61,$72,$67,$73,$2E,$2E
	.byte	$2E,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20,$20
	.byte	$20,$20,$20,$20,$20,$20,$76,$67,$61,$20,$63,$74,$72,$6C,$00
L00A3:
	.byte	$65,$78,$65,$63,$20,$30,$78,$25,$78,$20,$28,$30,$78,$25,$78,$20
	.byte	$30,$78,$25,$78,$20,$30,$78,$25,$78,$20,$30,$78,$25,$78,$29,$20
	.byte	$72,$65,$74,$75,$72,$6E,$20,$30,$78,$25,$78,$0D,$0A,$00
L0244:
	.byte	$67,$70,$69,$6F,$20,$69,$6E,$69,$74,$20,$5B,$67,$70,$69,$6F,$5F
	.byte	$6E,$75,$6D,$5D,$20,$5B,$69,$6E,$7C,$6F,$75,$74,$5D,$0D,$0A,$00
L0233:
	.byte	$75,$6E,$6B,$6E,$6F,$77,$6E,$20,$67,$70,$69,$6F,$20,$6E,$75,$6D
	.byte	$20,$5B,$25,$73,$5D,$0D,$0A,$00
L026F:
	.byte	$67,$70,$69,$6F,$20,$72,$65,$61,$64,$20,$72,$65,$74,$75,$72,$6E
	.byte	$20,$25,$64,$0D,$0A,$00
L025E:
	.byte	$75,$6E,$6B,$6E,$6F,$77,$6E,$20,$6D,$6F,$64,$65,$20,$5B,$25,$73
	.byte	$5D,$0D,$0A,$00
L0311:
	.byte	$69,$6C,$6C,$65,$67,$61,$6C,$20,$63,$6D,$64,$20,$5B,$25,$73,$5D
	.byte	$20,$0D,$0A,$00
L0075:
	.byte	$5B,$30,$78,$25,$78,$5D,$20,$3C,$2D,$20,$28,$30,$78,$25,$78,$29
	.byte	$0D,$0A,$00
L0128:
	.byte	$0D,$0A,$5B,$30,$78,$25,$30,$34,$78,$5D,$3A,$20,$00
L00D4	:=	L0128+0
L031C:
	.byte	$72,$65,$74,$75,$72,$6E,$20,$30,$78,$25,$78,$00
L00F9	:=	L0128+2
L00BD	:=	L0128+2
L02A4:
	.byte	$25,$73,$3A,$09,$09,$25,$73,$0D,$0A,$00
L0041:
	.byte	$5B,$30,$78,$25,$78,$5D,$3A,$20,$00
L00C9:
	.byte	$30,$78,$25,$30,$34,$78,$20,$00
L0321:
	.byte	$0D,$0A,$68,$63,$6F,$73,$23,$00
L004A	:=	L00A3+39
L0112:
	.byte	$25,$30,$32,$78,$20,$00
L0277:
	.byte	$77,$72,$69,$74,$65,$00
L0020:
	.byte	$64,$75,$6D,$70,$62,$00
L013F	:=	L0112+0
L001B:
	.byte	$64,$75,$6D,$70,$77,$00
L0268:
	.byte	$72,$65,$61,$64,$00
L0025	:=	L0028+47
L023C:
	.byte	$69,$6E,$69,$74,$00
L0034:
	.byte	$68,$65,$6C,$70,$00
L002F:
	.byte	$76,$67,$61,$00
L0256:
	.byte	$6F,$75,$74,$00
L002A:
	.byte	$70,$73,$32,$00
L0148:
	.byte	$20,$20,$20,$00
L0156:
	.byte	$25,$63,$00
L014B	:=	L0148+1
L024B:
	.byte	$69,$6E,$00
L0122	:=	L0156+0
L0117	:=	L0148+1
L0306	:=	L00A3+43
L028C	:=	L00A3+43
L015C	:=	L00A3+43
L00D9	:=	L00A3+43
L0016	:=	L031C+10
L0011	:=	L001B+4
L0281:
	.byte	$30,$00
L000C	:=	L000F+53

.segment	"BSS"

_argc:
	.res	1,$00

; ---------------------------------------------------------------
; long __near__ cmd_read (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cmd_read: near

.segment	"CODE"

	jsr     decsp3
	lda     _argv+2
	ldx     _argv+2+1
	jsr     pushax
	jsr     push0
	jsr     _strtoul
	ldy     #$01
	jsr     staxysp
	lda     #<(L0041)
	ldx     #>(L0041)
	jsr     pushax
	ldy     #$06
	jsr     pushwysp
	ldy     #$04
	jsr     _uart_printf
	ldy     #$02
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     (sp),y
	lda     #<(L004A)
	ldx     #>(L004A)
	jsr     pushax
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	ldy     #$04
	jsr     _uart_printf
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; long __near__ cmd_write (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cmd_write: near

.segment	"CODE"

	jsr     decsp7
	ldx     #$00
	lda     _argc
	cmp     #$03
	bcs     L0324
	dex
	stx     sreg
	stx     sreg+1
	txa
	jmp     incsp7
L0324:	lda     _argc
	jsr     decax2
	ldy     #$01
	jsr     staxysp
	cpx     #$00
	bne     L0056
	cmp     #$11
L0056:	bcs     L0057
	ldy     #$02
	jsr     ldaxysp
	jmp     L0059
L0057:	ldx     #$00
	lda     #$10
L0059:	ldy     #$01
	jsr     staxysp
	lda     _argv+2
	ldx     _argv+2+1
	jsr     pushax
	jsr     push0
	jsr     _strtoul
	ldy     #$03
	jsr     staxysp
	ldx     #$00
	txa
L0326:	ldy     #$05
	jsr     staxysp
	ldy     #$01
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	bcs     L0062
	ldy     #$06
	jsr     ldaxysp
	jsr     incax2
	jsr     aslax1
	clc
	adc     #<(_argv)
	tay
	txa
	adc     #>(_argv)
	tax
	tya
	jsr     pushw
	jsr     push0
	jsr     _strtoul
	ldy     #$00
	sta     (sp),y
	ldy     #$06
	jsr     ldaxysp
	clc
	ldy     #$03
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (sp),y
	sta     (ptr1),y
	lda     #<(L0075)
	ldx     #>(L0075)
	jsr     pushax
	ldy     #$08
	jsr     ldaxysp
	clc
	ldy     #$05
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	jsr     pushax
	ldy     #$04
	lda     (sp),y
	jsr     pusha0
	ldy     #$06
	jsr     _uart_printf
	ldy     #$06
	jsr     ldaxysp
	jsr     incax1
	jmp     L0326
L0062:	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; long __near__ cmd_exec (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cmd_exec: near

.segment	"CODE"

	ldy     #$10
	jsr     subysp
	lda     _argv+2
	ldx     _argv+2+1
	jsr     pushax
	jsr     push0
	jsr     _strtoul
	ldy     #$0A
	jsr     staxysp
	lda     _argv+4
	ldx     _argv+4+1
	jsr     pushax
	jsr     push0
	jsr     _strtoul
	ldy     #$08
	jsr     staxysp
	lda     _argv+6
	ldx     _argv+6+1
	jsr     pushax
	jsr     push0
	jsr     _strtoul
	ldy     #$06
	jsr     staxysp
	lda     _argv+8
	ldx     _argv+8+1
	jsr     pushax
	jsr     push0
	jsr     _strtoul
	ldy     #$04
	jsr     staxysp
	lda     _argv+10
	ldx     _argv+10+1
	jsr     pushax
	jsr     push0
	jsr     _strtoul
	ldy     #$02
	jsr     staxysp
	ldy     #$0B
	jsr     ldaxysp
	jsr     stax0sp
	jsr     pushax
	ldy     #$0D
	jsr     pushwysp
	ldy     #$0D
	jsr     pushwysp
	ldy     #$0D
	jsr     pushwysp
	ldy     #$0D
	jsr     pushwysp
	ldy     #$09
	jsr     ldaxysp
	jsr     callax
	jsr     incsp2
	ldy     #$0C
	jsr     steaxysp
	lda     #<(L00A3)
	ldx     #>(L00A3)
	jsr     pushax
	ldy     #$0F
	jsr     pushwysp
	ldy     #$0F
	jsr     pushwysp
	ldy     #$0F
	jsr     pushwysp
	ldy     #$0F
	jsr     pushwysp
	ldy     #$0F
	jsr     pushwysp
	ldy     #$1B
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$10
	jsr     _uart_printf
	ldy     #$0F
	jsr     ldeaxysp
	ldy     #$10
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; long __near__ cmd_dumpw (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cmd_dumpw: near

.segment	"CODE"

	ldy     #$0A
	jsr     subysp
	lda     _argv+2
	ldx     _argv+2+1
	jsr     pushax
	jsr     push0
	jsr     _strtoul
	ldy     #$02
	jsr     staxysp
	lda     _argv+4
	ldx     _argv+4+1
	jsr     pushax
	jsr     push0
	jsr     _strtoul
	jsr     stax0sp
	ldy     #$03
	jsr     ldaxysp
	ldy     #$04
	jsr     staxysp
	lda     #<(L00BD)
	ldx     #>(L00BD)
	jsr     pushax
	ldy     #$09
	jsr     pushwysp
	ldy     #$04
	jsr     _uart_printf
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	ldy     #$06
	jsr     steaxysp
L00C1:	ldy     #$09
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$05
	jsr     ldaxysp
	jsr     axulong
	jsr     tosulteax
	beq     L00C2
	lda     #<(L00C9)
	ldx     #>(L00C9)
	jsr     pushax
	ldy     #$09
	jsr     pushwysp
	ldy     #$0D
	jsr     ldeaxysp
	jsr     saveeax
	ldy     #$01
	jsr     inceaxy
	ldy     #$0A
	jsr     steaxysp
	jsr     resteax
	jsr     aslax1
	jsr     tosaddax
	jsr     pushw
	ldy     #$04
	jsr     _uart_printf
	ldy     #$09
	jsr     ldeaxysp
	jsr     pusheax
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	jsr     tosneeax
	beq     L00C1
	ldy     #$09
	jsr     ldeaxysp
	ldx     #$00
	and     #$03
	jsr     push0ax
	txa
	jsr     toseqeax
	beq     L00C1
	lda     #<(L00D4)
	ldx     #>(L00D4)
	jsr     pushax
	ldy     #$09
	jsr     pushwysp
	ldy     #$0D
	jsr     ldeaxysp
	jsr     aslax1
	jsr     tosaddax
	jsr     pushax
	ldy     #$04
	jsr     _uart_printf
	jmp     L00C1
L00C2:	lda     #<(L00D9)
	ldx     #>(L00D9)
	jsr     pushax
	ldy     #$02
	jsr     _uart_printf
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	ldy     #$0A
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; long __near__ cmd_dumpb (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cmd_dumpb: near

.segment	"CODE"

	ldy     #$22
	jsr     subysp
	lda     _argv+2
	ldx     _argv+2+1
	jsr     pushax
	jsr     push0
	jsr     _strtoul
	ldy     #$06
	jsr     staxysp
	lda     _argv+4
	ldx     _argv+4+1
	jsr     pushax
	jsr     push0
	jsr     _strtoul
	ldy     #$04
	jsr     staxysp
	ldy     #$07
	jsr     ldaxysp
	ldy     #$18
	jsr     staxysp
	ldy     #$05
	jsr     ldaxysp
	jsr     shrax4
	ldy     #$02
	jsr     staxysp
	ldy     #$04
	lda     (sp),y
	ldx     #$00
	and     #$0F
	jsr     stax0sp
	lda     #<(L00F9)
	ldx     #>(L00F9)
	jsr     pushax
	ldy     #$1D
	jsr     pushwysp
	ldy     #$04
	jsr     _uart_printf
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	ldy     #$1E
	jsr     steaxysp
L00FD:	ldy     #$21
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$07
	jsr     ldaxysp
	jsr     axulong
	jsr     tosulteax
	jeq     L00FE
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	ldy     #$1A
	jsr     steaxysp
L0105:	ldy     #$1D
	jsr     ldeaxysp
	cmp     #$10
	txa
	sbc     #$00
	lda     sreg
	sbc     #$00
	lda     sreg+1
	sbc     #$00
	bcs     L0106
	lda     #$08
	jsr     leaa0sp
	ldy     #$1A
	clc
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	jsr     pushax
	ldy     #$1D
	jsr     pushwysp
	ldy     #$25
	jsr     ldeaxysp
	jsr     shleax4
	jsr     pusheax
	ldy     #$25
	jsr     ldeaxysp
	jsr     tosaddeax
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     staspidx
	lda     #<(L0112)
	ldx     #>(L0112)
	jsr     pushax
	lda     #$0A
	jsr     leaa0sp
	ldy     #$1C
	clc
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	jsr     pusha0
	ldy     #$04
	jsr     _uart_printf
	ldy     #$1D
	jsr     ldeaxysp
	jsr     saveeax
	ldy     #$01
	jsr     inceaxy
	ldy     #$1A
	jsr     steaxysp
	jsr     resteax
	jmp     L0105
L0106:	lda     #<(L0117)
	ldx     #>(L0117)
	jsr     pushax
	ldy     #$02
	jsr     _uart_printf
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	ldy     #$1A
	jsr     steaxysp
L0119:	ldy     #$1D
	jsr     ldeaxysp
	cmp     #$10
	txa
	sbc     #$00
	lda     sreg
	sbc     #$00
	lda     sreg+1
	sbc     #$00
	bcs     L011A
	lda     #<(L0122)
	ldx     #>(L0122)
	jsr     pushax
	lda     #$0A
	jsr     leaa0sp
	ldy     #$1C
	clc
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     pusha
	jsr     _cook
	jsr     pushax
	ldy     #$04
	jsr     _uart_printf
	ldy     #$1D
	jsr     ldeaxysp
	jsr     saveeax
	ldy     #$01
	jsr     inceaxy
	ldy     #$1A
	jsr     steaxysp
	jsr     resteax
	jmp     L0119
L011A:	lda     #<(L0128)
	ldx     #>(L0128)
	jsr     pushax
	ldy     #$1D
	jsr     pushwysp
	ldy     #$25
	jsr     ldeaxysp
	ldy     #$01
	jsr     inceaxy
	jsr     shleax4
	jsr     tosaddax
	jsr     pushax
	ldy     #$04
	jsr     _uart_printf
	ldy     #$21
	jsr     ldeaxysp
	jsr     saveeax
	ldy     #$01
	jsr     inceaxy
	ldy     #$1E
	jsr     steaxysp
	jsr     resteax
	jmp     L00FD
L00FE:	ldy     #$00
	lda     (sp),y
	iny
	ora     (sp),y
	jeq     L014E
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	ldy     #$1A
	jsr     steaxysp
L0130:	ldy     #$1D
	jsr     ldeaxysp
	cmp     #$10
	txa
	sbc     #$00
	lda     sreg
	sbc     #$00
	lda     sreg+1
	sbc     #$00
	jcs     L0131
	ldy     #$1D
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$05
	jsr     ldaxysp
	jsr     axulong
	jsr     tosulteax
	beq     L0138
	lda     #$08
	jsr     leaa0sp
	ldy     #$1A
	clc
	adc     (sp),y
	pha
	txa
	iny
	adc     (sp),y
	tax
	pla
	jsr     pushax
	ldy     #$1D
	jsr     pushwysp
	ldy     #$25
	jsr     ldeaxysp
	jsr     shleax4
	jsr     pusheax
	ldy     #$25
	jsr     ldeaxysp
	jsr     tosaddeax
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     staspidx
	lda     #<(L013F)
	ldx     #>(L013F)
	jsr     pushax
	lda     #$0A
	jsr     leaa0sp
	ldy     #$1C
	clc
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	jsr     pusha0
	ldy     #$04
	jmp     L0327
L0138:	lda     #$08
	jsr     leaa0sp
	ldy     #$1A
	clc
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     #$20
	ldy     #$00
	sta     (ptr1),y
	lda     #<(L0148)
	ldx     #>(L0148)
	jsr     pushax
	ldy     #$02
L0327:	jsr     _uart_printf
	ldy     #$1D
	jsr     ldeaxysp
	jsr     saveeax
	ldy     #$01
	jsr     inceaxy
	ldy     #$1A
	jsr     steaxysp
	jsr     resteax
	jmp     L0130
L0131:	lda     #<(L014B)
	ldx     #>(L014B)
	jsr     pushax
	ldy     #$02
	jsr     _uart_printf
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	ldy     #$1A
	jsr     steaxysp
L014D:	ldy     #$1D
	jsr     ldeaxysp
	cmp     #$10
	txa
	sbc     #$00
	lda     sreg
	sbc     #$00
	lda     sreg+1
	sbc     #$00
	bcs     L014E
	lda     #<(L0156)
	ldx     #>(L0156)
	jsr     pushax
	lda     #$0A
	jsr     leaa0sp
	ldy     #$1C
	clc
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     pusha
	jsr     _cook
	jsr     pushax
	ldy     #$04
	jsr     _uart_printf
	ldy     #$1D
	jsr     ldeaxysp
	jsr     saveeax
	ldy     #$01
	jsr     inceaxy
	ldy     #$1A
	jsr     steaxysp
	jsr     resteax
	jmp     L014D
L014E:	lda     #<(L015C)
	ldx     #>(L015C)
	jsr     pushax
	ldy     #$02
	jsr     _uart_printf
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	ldy     #$22
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; long __near__ cmd_gpio (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cmd_gpio: near

.segment	"CODE"

	jsr     decsp3
	lda     _argv+4
	ldx     _argv+4+1
	jsr     pushax
	jsr     _gi_get
	ldy     #$01
	jsr     staxysp
	cpx     #$00
	bne     L022F
	cmp     #$00
	bne     L022F
	lda     #<(L0233)
	ldx     #>(L0233)
	jsr     pushax
	lda     _argv+4
	ldx     _argv+4+1
	jsr     pushax
	ldy     #$04
	jsr     _uart_printf
	ldx     #$FF
	stx     sreg
	stx     sreg+1
	txa
	jmp     incsp3
L022F:	lda     _argv+2
	ldx     _argv+2+1
	jsr     pushax
	lda     #<(L023C)
	ldx     #>(L023C)
	jsr     _strcmp
	cpx     #$00
	jne     L0238
	cmp     #$00
	jne     L0238
	lda     _argv+6
	ora     _argv+6+1
	bne     L023F
	lda     #<(L0244)
	ldx     #>(L0244)
	jsr     pushax
	ldy     #$02
	jsr     _uart_printf
	ldx     #$FF
	stx     sreg
	stx     sreg+1
	txa
	jmp     incsp3
L023F:	lda     _argv+6
	ldx     _argv+6+1
	jsr     pushax
	lda     #<(L024B)
	ldx     #>(L024B)
	jsr     _strcmp
	cpx     #$00
	bne     L0247
	cmp     #$00
	bne     L0247
	ldy     #$02
	jsr     ldaxysp
	ldy     #$13
	jsr     ldeaxidx
	jsr     pusheax
	lda     #$00
	jsr     pusha
	jsr     _gpio_init
	jmp     L0287
L0247:	lda     _argv+6
	ldx     _argv+6+1
	jsr     pushax
	lda     #<(L0256)
	ldx     #>(L0256)
	jsr     _strcmp
	cpx     #$00
	bne     L0252
	cmp     #$00
	bne     L0252
	ldy     #$02
	jsr     ldaxysp
	ldy     #$13
	jsr     ldeaxidx
	jsr     pusheax
	lda     #$01
	jsr     pusha
	jsr     _gpio_init
	jmp     L0287
L0252:	lda     #<(L025E)
	ldx     #>(L025E)
	jsr     pushax
	lda     _argv+6
	ldx     _argv+6+1
	jsr     pushax
	ldy     #$04
	jsr     _uart_printf
	ldx     #$FF
	stx     sreg
	stx     sreg+1
	txa
	jmp     incsp3
L0238:	lda     _argv+2
	ldx     _argv+2+1
	jsr     pushax
	lda     #<(L0268)
	ldx     #>(L0268)
	jsr     _strcmp
	cpx     #$00
	bne     L0264
	cmp     #$00
	bne     L0264
	ldy     #$02
	jsr     ldaxysp
	ldy     #$13
	jsr     ldeaxidx
	jsr     pusheax
	jsr     _gpio_read
	ldy     #$00
	sta     (sp),y
	lda     #<(L026F)
	ldx     #>(L026F)
	jsr     pushax
	ldy     #$02
	lda     (sp),y
	jsr     pusha0
	ldy     #$04
	jsr     _uart_printf
	jmp     L0287
L0264:	lda     _argv+2
	ldx     _argv+2+1
	jsr     pushax
	lda     #<(L0277)
	ldx     #>(L0277)
	jsr     _strcmp
	cpx     #$00
	bne     L0287
	cmp     #$00
	bne     L0287
	ldy     #$02
	jsr     ldaxysp
	ldy     #$13
	jsr     ldeaxidx
	jsr     pusheax
	lda     #$01
	jsr     pusha
	jsr     _gpio_init
	lda     _argv+6
	ldx     _argv+6+1
	jsr     pushax
	lda     #<(L0281)
	ldx     #>(L0281)
	jsr     _strcmp
	cpx     #$00
	bne     L027D
	cmp     #$00
	bne     L027D
	ldy     #$02
	jsr     ldaxysp
	ldy     #$13
	jsr     ldeaxidx
	jsr     pusheax
	lda     #$00
	jmp     L0329
L027D:	ldy     #$02
	jsr     ldaxysp
	ldy     #$13
	jsr     ldeaxidx
	jsr     pusheax
	lda     #$01
L0329:	jsr     pusha
	jsr     _gpio_write
L0287:	lda     #<(L028C)
	ldx     #>(L028C)
	jsr     pushax
	ldy     #$02
	jsr     _uart_printf
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; long __near__ cmd_ps2 (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cmd_ps2: near

.segment	"CODE"

	ldy     #$00
	jsr     _ps2_process
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	rts

.endproc

; ---------------------------------------------------------------
; long __near__ cmd_vga (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cmd_vga: near

.segment	"CODE"

	ldx     #$00
	lda     #$80
	jsr     push0ax
	ldy     #$04
	jsr     _vga_ctrl
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	rts

.endproc

; ---------------------------------------------------------------
; long __near__ cmd_help (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cmd_help: near

.segment	"CODE"

	jsr     decsp4
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	jsr     steax0sp
L0297:	jsr     ldeax0sp
	cmp     #$09
	txa
	sbc     #$00
	lda     sreg
	sbc     #$00
	lda     sreg+1
	sbc     #$00
	bcs     L0298
	lda     #<(L02A4)
	ldx     #>(L02A4)
	jsr     pushax
	ldy     #$05
	jsr     ldeaxysp
	jsr     mulax6
	clc
	adc     #<(_ci)
	tay
	txa
	adc     #>(_ci)
	tax
	tya
	jsr     pushw
	ldy     #$07
	jsr     ldeaxysp
	jsr     mulax6
	clc
	adc     #<(_ci)
	tay
	txa
	adc     #>(_ci)
	tax
	tya
	ldy     #$05
	jsr     pushwidx
	ldy     #$06
	jsr     _uart_printf
	jsr     ldeax0sp
	jsr     saveeax
	ldy     #$01
	jsr     inceaxy
	jsr     steax0sp
	jsr     resteax
	jmp     L0297
L0298:	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ cook (unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_cook: near

.segment	"CODE"

	ldy     #$00
	lda     (sp),y
	cmp     #$20
	ldx     #$00
	bcc     L032D
	lda     (sp),y
	cmp     #$7F
	bcs     L032D
	jmp     incsp1
L032D:	lda     #$2E
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; __near__ struct gpio_info * __near__ gi_get (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_gi_get: near

.segment	"CODE"

	jsr     decsp2
	ldy     #$02
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L0211
	tax
	jmp     incsp4
L0211:	ldx     #$00
	txa
L0330:	jsr     stax0sp
	ldy     #$01
	lda     (sp),y
	cmp     #$00
	bne     L021F
	dey
	lda     (sp),y
	cmp     #$20
L021F:	bcs     L0216
	jsr     pushw0sp
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_gi)
	tay
	txa
	adc     #>(_gi)
	tax
	tya
	jsr     pushax
	ldy     #$05
	jsr     ldaxysp
	jsr     _strcmp
	cpx     #$00
	bne     L0217
	cmp     #$00
	bne     L0217
	jsr     pushw0sp
	lda     #$14
	jsr     tosmula0
	clc
	adc     #<(_gi)
	tay
	txa
	adc     #>(_gi)
	tax
	tya
	jmp     incsp4
L0217:	jsr     ldax0sp
	jsr     incax1
	jmp     L0330
L0216:	ldx     #$00
	txa
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; long __near__ parse_cmd (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_parse_cmd: near

.segment	"CODE"

	jsr     decsp8
	lda     #>(_argv)
	sta     ptr1+1
	lda     #<(_argv)
	sta     ptr1
	lda     #$00
	ldy     #$0B
L0331:	sta     (ptr1),y
	dey
	bpl     L0331
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	jsr     steax0sp
	ldy     #$04
	jsr     steaxysp
L02B5:	ldy     #$0B
	jsr     pushwysp
	ldy     #$09
	jsr     ldeaxysp
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	bne     L02BF
	jmp     L0336
L02BD:	ldy     #$07
	jsr     ldeaxysp
	jsr     saveeax
	ldy     #$01
	jsr     inceaxy
	ldy     #$04
	jsr     steaxysp
	jsr     resteax
L02BF:	ldy     #$0B
	jsr     pushwysp
	ldy     #$09
	jsr     ldeaxysp
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$20
	beq     L02BD
	jsr     ldeax0sp
	jsr     saveeax
	ldy     #$01
	jsr     inceaxy
	jsr     steax0sp
	jsr     resteax
	jsr     aslax1
	clc
	adc     #<(_argv)
	tay
	txa
	adc     #>(_argv)
	tax
	tya
	jsr     pushax
	ldy     #$0D
	jsr     pushwysp
	ldy     #$0B
	jsr     ldeaxysp
	jsr     tosaddax
	ldy     #$00
	jsr     staxspidx
	jsr     ldeax0sp
	jsr     pusheax
	ldx     #$00
	stx     sreg
	stx     sreg+1
	lda     #$06
	jsr     toseqeax
	beq     L02CC
	jmp     L02B6
L02CA:	ldy     #$07
	jsr     ldeaxysp
	jsr     saveeax
	ldy     #$01
	jsr     inceaxy
	ldy     #$04
	jsr     steaxysp
	jsr     resteax
L02CC:	ldy     #$0B
	jsr     pushwysp
	ldy     #$09
	jsr     ldeaxysp
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$20
	jeq     L02B5
	ldy     #$0B
	jsr     pushwysp
	ldy     #$09
	jsr     ldeaxysp
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	bne     L02CA
	jmp     L02B5
L02B6:	ldy     #$00
L0336:	lda     (sp),y
	sta     _argc
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	ldy     #$04
	jsr     steaxysp
L02D5:	ldy     #$0B
	jsr     pushwysp
	ldy     #$09
	jsr     ldeaxysp
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1,x)
	beq     L0337
	ldy     #$0B
	jsr     pushwysp
	ldy     #$09
	jsr     ldeaxysp
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	cmp     #$20
	bne     L02D7
	ldy     #$0B
	jsr     pushwysp
	ldy     #$09
	jsr     ldeaxysp
	jsr     tosaddax
	sta     sreg
	stx     sreg+1
	lda     #$00
	tay
	sta     (sreg),y
L02D7:	ldy     #$07
	jsr     ldeaxysp
	jsr     saveeax
	ldy     #$01
	jsr     inceaxy
	ldy     #$04
	jsr     steaxysp
	jsr     resteax
	jmp     L02D5
L0337:	sta     sreg
	sta     sreg+1
	ldy     #$0A
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; long __near__ get_cmd_index (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_get_cmd_index: near

.segment	"CODE"

	jsr     decsp4
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	jsr     steax0sp
L02E6:	jsr     ldeax0sp
	cmp     #$09
	txa
	sbc     #$00
	lda     sreg
	sbc     #$00
	lda     sreg+1
	sbc     #$00
	bcs     L02E7
	jsr     ldeax0sp
	jsr     mulax6
	clc
	adc     #<(_ci)
	tay
	txa
	adc     #>(_ci)
	tax
	tya
	jsr     pushw
	ldy     #$07
	jsr     ldaxysp
	jsr     _strcmp
	cpx     #$00
	bne     L02E8
	cmp     #$00
	bne     L02E8
	jsr     ldeax0sp
	jmp     incsp6
L02E8:	jsr     ldeax0sp
	jsr     saveeax
	ldy     #$01
	jsr     inceaxy
	jsr     steax0sp
	jsr     resteax
	jmp     L02E6
L02E7:	ldx     #$FF
	stx     sreg
	stx     sreg+1
	txa
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; long __near__ shell (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_shell: near

.segment	"RODATA"

L0304:
	.word	$0000
L0317:
	.word	$0000

.segment	"CODE"

	jsr     decsp8
	jsr     pushl0
	ldy     #$0D
	jsr     ldaxysp
	jsr     _strlen
	jsr     axulong
	ldy     #$04
	jsr     steaxysp
	ldy     #$07
	jsr     ldeaxysp
	jsr     pusheax
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	jsr     toseqeax
	beq     L02FF
	ldx     #$00
	txa
	jsr     steax0sp
	jmp     L0303
L02FF:	lda     #<(L0306)
	ldx     #>(L0306)
	jsr     pushax
	ldy     #$02
	jsr     _uart_printf
	ldy     #$0F
	jsr     pushwysp
	jsr     _parse_cmd
	lda     _argv
	ldx     _argv+1
	jsr     pushax
	jsr     _get_cmd_index
	ldy     #$08
	jsr     steaxysp
	jsr     pusheax
	ldx     #$FF
	stx     sreg
	stx     sreg+1
	txa
	jsr     toseqeax
	beq     L030A
	lda     #<(L0311)
	ldx     #>(L0311)
	jsr     pushax
	lda     _argv
	ldx     _argv+1
	jsr     pushax
	ldy     #$04
	jsr     _uart_printf
	ldx     #$FF
	stx     sreg
	stx     sreg+1
	txa
	jsr     steax0sp
	jmp     L0303
L030A:	ldy     #$0B
	jsr     ldeaxysp
	jsr     mulax6
	clc
	adc     #<(_ci)
	tay
	txa
	adc     #>(_ci)
	tax
	tya
	ldy     #$03
	jsr     ldaxidx
	jsr     callax
	jsr     steax0sp
	lda     #<(L031C)
	ldx     #>(L031C)
	jsr     pushax
	ldy     #$05
	jsr     ldeaxysp
	jsr     pusheax
	ldy     #$06
	jsr     _uart_printf
L0303:	lda     #<(L0321)
	ldx     #>(L0321)
	jsr     pushax
	ldy     #$02
	jsr     _uart_printf
	jsr     ldeax0sp
	ldy     #$0E
	jmp     addysp

.endproc

